# Generated by Django 5.1.7 on 2025-07-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
